### PR TITLE
Feature/feat static cat

### PR DESCRIPTION
**Pull request by StanislasGuinel**
PR to add feat_static_cat support:
- feat_static_cat are used to group similar timeseries together: a vector embedding of these categories is found during training

Because I merged with feature/timestamp-preparation (sorry about that), we should wait for the feature/timestamp-preparation branch to be merged with release/1.0 before reviewing this one.

### CODE REVIEW

**Comment by alexcombessie** [comment]
Hi @StanislasGuinel,

Really interesting idea! In terms of UX, I am not in favour of implementing this as an advanced parameter in the Train recipe. 

In the typical case of retail product forecasting, you have one table with sales per product and per store, and another one with just product information. Forcing users to create a copy of all product information along with time-dependent sales doesn't look very natural.

 Instead, I would recommend having a "Static features" optional input dataset, for both recipes.

Also, I think it would be interesting running another multivariate benchmark to study the effect of adding time series identifiers as static features by default. 

Cheers,

Alex

**Comment by alexcombessie** [comment]
Hi @StanislasGuinel,

Shall we say that this is for v1.x? Can you create a CH story to keep track of it?

Cheers,

Alex

**Comment by StanislasGuinel** [comment]
yes I agree, as it requires proper benchmark. Will put in the backlog epic

**Comment by StanislasGuinel** [comment]
Not going to implement yet

**Pull request closed without merging**
